[www]
; user qnd groups on which php will execute
user = www-data
group = www-data

listen = 0.0.0.0:9000

listen.owner = www-data
listen.group = www-data

; "dynamic" means PHP-FPM adjust dynamicaly process number
pm = dynamic

; max process number able to launch
pm.max_children = 5

; process at start
pm.start_servers = 2

; min to keep inactive
pm.min_spare_servers = 1

; max to keep inactive
pm.max_spare_servers = 3